In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("C:/Users/Prabhjyot/Desktop/Data Science_ML/Practice/ML/AB_NYC_2019.csv")
print(df.shape)
print(df.info())

(48895, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
id                                48895 non-null int64
name                              48879 non-null object
host_id                           48895 non-null int64
host_name                         48874 non-null object
neighbourhood_group               48895 non-null object
neighbourhood                     48895 non-null object
latitude                          48895 non-null float64
longitude                         48895 non-null float64
room_type                         48895 non-null object
price                             48895 non-null int64
minimum_nights                    48895 non-null int64
number_of_reviews                 48895 non-null int64
last_review                       38843 non-null object
reviews_per_month                 38843 non-null float64
calculated_host_listings_count    48895 non-null int64
availability_365                  48895 no

In [9]:
# Hence, we see that there are 16 columns and 48895 rows
# Missing values are there in columns name, host_name, last_review, reviews_per_month. 
# ID, name and host_name column has no affect on Price. Hence can be removed
df1 = df.drop(['id', 'name', 'host_name'],axis=1)
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 13 columns):
host_id                           48895 non-null int64
neighbourhood_group               48895 non-null object
neighbourhood                     48895 non-null object
latitude                          48895 non-null float64
longitude                         48895 non-null float64
room_type                         48895 non-null object
price                             48895 non-null int64
minimum_nights                    48895 non-null int64
number_of_reviews                 48895 non-null int64
last_review                       38843 non-null object
reviews_per_month                 38843 non-null float64
calculated_host_listings_count    48895 non-null int64
availability_365                  48895 non-null int64
dtypes: float64(3), int64(6), object(4)
memory usage: 4.8+ MB
None


In [10]:
# now we have null values in last_review and reviews_per_month
df1.isnull().sum()

host_id                               0
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [11]:
# number of null values in last_review and reviews_per_months is same. hence there seems to be a relation. However, we cannot imput 
# last_review but we can for reviews_per_month
df1.head(10)

host_id neighbourhood_group       neighbourhood  latitude  longitude  \
0     2787            Brooklyn          Kensington  40.64749  -73.97237   
1     2845           Manhattan             Midtown  40.75362  -73.98377   
2     4632           Manhattan              Harlem  40.80902  -73.94190   
3     4869            Brooklyn        Clinton Hill  40.68514  -73.95976   
4     7192           Manhattan         East Harlem  40.79851  -73.94399   
5     7322           Manhattan         Murray Hill  40.74767  -73.97500   
6     7356            Brooklyn  Bedford-Stuyvesant  40.68688  -73.95596   
7     8967           Manhattan      Hell's Kitchen  40.76489  -73.98493   
8     7490           Manhattan     Upper West Side  40.80178  -73.96723   
9     7549           Manhattan           Chinatown  40.71344  -73.99037   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   
5  Entire home/apt    200               3                 74  2019-06-22   
6     Private room     60              45                 49  2017-10-05   
7     Private room     79               2                430  2019-06-24   
8     Private room     79               2                118  2017-07-21   
9  Entire home/apt    150               1                160  2019-06-09   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0  
5               0.59                               1               129  
6               0.40                               1                 0  
7               3.47                               1               220  
8               0.99                               1                 0  
9               1.33                               4               188

In [12]:
df1.loc[df1['reviews_per_month'].isnull(),'reviews_per_month']=0
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 13 columns):
host_id                           48895 non-null int64
neighbourhood_group               48895 non-null object
neighbourhood                     48895 non-null object
latitude                          48895 non-null float64
longitude                         48895 non-null float64
room_type                         48895 non-null object
price                             48895 non-null int64
minimum_nights                    48895 non-null int64
number_of_reviews                 48895 non-null int64
last_review                       38843 non-null object
reviews_per_month                 48895 non-null float64
calculated_host_listings_count    48895 non-null int64
availability_365                  48895 non-null int64
dtypes: float64(3), int64(6), object(4)
memory usage: 4.8+ MB


In [14]:
# remove last_review as we have dealt with reviews_per_month by imputing missing values with 0
df1 = df1.drop('last_review',axis = 1)
df1.head()

host_id neighbourhood_group neighbourhood  latitude  longitude  \
0     2787            Brooklyn    Kensington  40.64749  -73.97237   
1     2845           Manhattan       Midtown  40.75362  -73.98377   
2     4632           Manhattan        Harlem  40.80902  -73.94190   
3     4869            Brooklyn  Clinton Hill  40.68514  -73.95976   
4     7192           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews  \
0     Private room    149               1                  9   
1  Entire home/apt    225               1                 45   
2     Private room    150               3                  0   
3  Entire home/apt     89               1                270   
4  Entire home/apt     80              10                  9   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2               0.00                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [15]:
# analyse the statistics of price group by neighbourhood. we observe there is minimum price as 0
df1.groupby('neighbourhood_group')['price'].describe()

count        mean         std   min   25%    50%  \
neighbourhood_group                                                       
Bronx                 1091.0   87.496792  106.709349   0.0  45.0   65.0   
Brooklyn             20104.0  124.383207  186.873538   0.0  60.0   90.0   
Manhattan            21661.0  196.875814  291.383183   0.0  95.0  150.0   
Queens                5666.0   99.517649  167.102155  10.0  50.0   75.0   
Staten Island          373.0  114.812332  277.620403  13.0  50.0   75.0   

                       75%      max  
neighbourhood_group                  
Bronx                 99.0   2500.0  
Brooklyn             150.0  10000.0  
Manhattan            220.0  10000.0  
Queens               110.0  10000.0  
Staten Island        110.0   5000.0

In [16]:
# analyse the statistics of minimum nights group by neighbourhood
df1.groupby('neighbourhood_group')['minimum_nights'].describe()

count      mean        std  min  25%  50%  75%     max
neighbourhood_group                                                          
Bronx                 1091.0  4.560953  15.631792  1.0  1.0  2.0  3.0   365.0
Brooklyn             20104.0  6.056556  17.632726  1.0  2.0  3.0  5.0   999.0
Manhattan            21661.0  8.579151  24.050857  1.0  1.0  3.0  6.0  1250.0
Queens                5666.0  5.181433  15.028725  1.0  1.0  2.0  3.0   500.0
Staten Island          373.0  4.831099  19.727605  1.0  1.0  2.0  3.0   365.0

In [20]:
# As price cannot be 0 and minimum nights cannot be more than 365; hence we remove these rows
df1 = df1[df1['price']>0]
df1 = df1[df1['minimum_nights']<=365]
df1.info()
df1.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48870 entries, 0 to 48894
Data columns (total 12 columns):
host_id                           48870 non-null int64
neighbourhood_group               48870 non-null object
neighbourhood                     48870 non-null object
latitude                          48870 non-null float64
longitude                         48870 non-null float64
room_type                         48870 non-null object
price                             48870 non-null int64
minimum_nights                    48870 non-null int64
number_of_reviews                 48870 non-null int64
reviews_per_month                 48870 non-null float64
calculated_host_listings_count    48870 non-null int64
availability_365                  48870 non-null int64
dtypes: float64(3), int64(6), object(3)
memory usage: 4.8+ MB


host_id neighbourhood_group neighbourhood  latitude  longitude  \
0     2787            Brooklyn    Kensington  40.64749  -73.97237   
1     2845           Manhattan       Midtown  40.75362  -73.98377   
2     4632           Manhattan        Harlem  40.80902  -73.94190   
3     4869            Brooklyn  Clinton Hill  40.68514  -73.95976   
4     7192           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews  \
0     Private room    149               1                  9   
1  Entire home/apt    225               1                 45   
2     Private room    150               3                  0   
3  Entire home/apt     89               1                270   
4  Entire home/apt     80              10                  9   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2               0.00                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [21]:
# analyse the statistics of availability_365 as per neighbourhood
df1.groupby('neighbourhood_group')['availability_365'].describe()

count        mean         std  min   25%    50%  \
neighbourhood_group                                                      
Bronx                 1090.0  165.794495  135.304079  0.0  37.0  148.0   
Brooklyn             20089.0  100.159739  126.243695  0.0   0.0   28.0   
Manhattan            21654.0  111.929667  132.641048  0.0   0.0   36.0   
Queens                5664.0  144.422493  135.528910  0.0   2.0   98.0   
Staten Island          373.0  199.678284  131.852000  0.0  78.0  219.0   

                        75%    max  
neighbourhood_group                 
Bronx                313.75  365.0  
Brooklyn             188.00  365.0  
Manhattan            230.00  365.0  
Queens               286.00  365.0  
Staten Island        333.00  365.0

In [22]:
# now data is ready for prediction. Calculate pairwise correlation matrix to see how 
#different variables are related to price
corr = df1.corr()
corr.style.background_gradient(cmap='coolwarm').set_precision(2)


In [36]:
# one hot encoding for categorical variables using get dummies
df1 = pd.get_dummies(df1,prefix_sep='_', drop_first=True)
df1.head()




host_id  neighbourhood_group  neighbourhood  latitude  longitude  \
0     2787                    1            108  40.64749  -73.97237   
1     2845                    2            127  40.75362  -73.98377   
2     4632                    2             94  40.80902  -73.94190   
3     4869                    1             41  40.68514  -73.95976   
4     7192                    2             61  40.79851  -73.94399   

   room_type  price  minimum_nights  number_of_reviews  reviews_per_month  \
0          1    149               1                  9               0.21   
1          0    225               1                 45               0.38   
2          1    150               3                  0               0.00   
3          0     89               1                270               4.64   
4          0     80              10                  9               0.10   

   calculated_host_listings_count  availability_365  
0                               6               365  
1                               2               355  
2                               1               365  
3                               1               194  
4                               1                 0

In [37]:
# VIF calculation

pd.DataFrame(np.linalg.inv(corr.corr().values), index = corr.index, columns=corr.columns)


host_id      latitude     longitude  \
host_id                        -2.140111e+15 -2.235303e+15 -2.929245e+15   
latitude                       -2.235303e+15 -2.334728e+15 -3.059536e+15   
longitude                      -2.929245e+15 -3.059536e+15 -4.009358e+15   
price                          -2.983960e+15 -3.116686e+15 -4.084250e+15   
minimum_nights                 -2.854844e+15 -2.981826e+15 -3.907524e+15   
number_of_reviews              -3.382915e+15 -3.533385e+15 -4.630312e+15   
reviews_per_month              -8.917696e+14 -9.314352e+14 -1.220596e+15   
calculated_host_listings_count -2.277405e+15 -2.378703e+15 -3.117163e+15   
availability_365               -2.027998e+14 -2.118203e+14 -2.775791e+14   

                                       price  minimum_nights  \
host_id                        -2.983960e+15   -2.854844e+15   
latitude                       -3.116686e+15   -2.981826e+15   
longitude                      -4.084250e+15   -3.907524e+15   
price                          -4.160540e+15   -3.980513e+15   
minimum_nights                 -3.980513e+15   -3.808275e+15   
number_of_reviews              -4.716803e+15   -4.512706e+15   
reviews_per_month              -1.243396e+15   -1.189594e+15   
calculated_host_listings_count -3.175389e+15   -3.037990e+15   
availability_365               -2.827641e+14   -2.705288e+14   

                                number_of_reviews  reviews_per_month  \
host_id                             -3.382915e+15      -8.917696e+14   
latitude                            -3.533385e+15      -9.314352e+14   
longitude                           -4.630312e+15      -1.220596e+15   
price                               -4.716803e+15      -1.243396e+15   
minimum_nights                      -4.512706e+15      -1.189594e+15   
number_of_reviews                   -5.347437e+15      -1.409637e+15   
reviews_per_month                   -1.409637e+15      -3.715942e+14   
calculated_host_listings_count      -3.599938e+15      -9.489790e+14   
availability_365                    -3.205695e+14      -8.450527e+13   

                                calculated_host_listings_count  \
host_id                                          -2.277405e+15   
latitude                                         -2.378703e+15   
longitude                                        -3.117163e+15   
price                                            -3.175389e+15   
minimum_nights                                   -3.037990e+15   
number_of_reviews                                -3.599938e+15   
reviews_per_month                                -9.489790e+14   
calculated_host_listings_count                   -2.423507e+15   
availability_365                                 -2.158099e+14   

                                availability_365  
host_id                            -2.027998e+14  
latitude                           -2.118203e+14  
longitude                          -2.775791e+14  
price                              -2.827641e+14  
minimum_nights                     -2.705288e+14  
number_of_reviews                  -3.205695e+14  
reviews_per_month                  -8.450527e+13  
calculated_host_listings_count     -2.158099e+14  
availability_365                   -1.921758e+13

In [54]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X = df1.drop('price', axis=1)
print(X.head())

Price = df1['price']
#Features_train, Features_test, Price_train, Price_test = train_test_split(Features, Price, test_size=0.30, random_state=42)
X_train, X_test, Price_train, Price_test = train_test_split(X, Price, test_size=0.3, random_state=42)

   host_id  neighbourhood_group  neighbourhood  latitude  longitude  \
0     2787                    1            108  40.64749  -73.97237   
1     2845                    2            127  40.75362  -73.98377   
2     4632                    2             94  40.80902  -73.94190   
3     4869                    1             41  40.68514  -73.95976   
4     7192                    2             61  40.79851  -73.94399   

   room_type  minimum_nights  number_of_reviews  reviews_per_month  \
0          1               1                  9               0.21   
1          0               1                 45               0.38   
2          1               3                  0               0.00   
3          0               1                270               4.64   
4          0              10                  9               0.10   

   calculated_host_listings_count  availability_365  
0                               6               365  
1                               2           

In [55]:
print("X", X.shape)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X (48870, 11)
X_train: (34209, 11)
X_test: (14661, 11)


In [56]:
from sklearn.linear_model import LinearRegression

print("\nLINEAR (subset)")
rgr = LinearRegression(normalize=True)
rgr.fit(X_train, Price_train)
print("model:", rgr)
print("coeffs:", rgr.coef_)
print("intercept:", rgr.intercept_)

#Evaluate the predictions of the model
Price_predictions_regression = rgr.predict(X_test)
print('R squared:', rgr.score(X_test, Price_test))
print(Price_predictions_regression[:10])
print(Price_test[:10])

Price_predictions_regression


LINEAR (subset)
model: LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)
coeffs: [ 8.78182173e-08  9.31779024e+00  7.85386983e-02  1.40635056e+02
 -6.19313540e+02 -1.02038153e+02 -1.92797055e-01 -2.01788181e-01
 -4.08334904e+00 -1.01330921e-01  1.98453094e-01]
intercept: -51364.95003423738
R squared: 0.07545358777141642
[100.29049932 218.15769999 267.52344489 183.01421766 222.14861915
 126.5823837  247.54960307 171.61454915 106.23490947 106.03986615]
9630      45
3794      85
16206    192
16899    120
12274    190
23433     79
20771    165
41065     99
42025     44
16440     65
Name: price, dtype: int64


array([100.29049932, 218.15769999, 267.52344489, ..., 260.23769631,
        57.33947068, 218.8335048 ])

In [57]:
print("\n\nRIDGE")
from sklearn.linear_model import Ridge
ridge = Ridge(alpha = 0.001, normalize=True)
ridge.fit(X_train, Price_train)
print("model:", ridge)
print("ridge coeffs:", ridge.coef_)
print("ridge intercept:", ridge.intercept_)
Price_predictions = ridge.predict(X_test)
print('Ridge R squared:', ridge.score(X_test, Price_test))
print(Price_predictions_regression[:10])
print(Price_test[:10])




RIDGE
model: Ridge(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=True, random_state=None, solver='auto', tol=0.001)
ridge coeffs: [ 8.76932535e-08  9.31186303e+00  7.85818944e-02  1.40443837e+02
 -6.18746031e+02 -1.01935172e+02 -1.91912126e-01 -2.01530514e-01
 -4.07963413e+00 -1.00677606e-01  1.98168215e-01]
ridge intercept: -51315.22012876494
Ridge R squared: 0.07545682698177003
[100.29049932 218.15769999 267.52344489 183.01421766 222.14861915
 126.5823837  247.54960307 171.61454915 106.23490947 106.03986615]
9630      45
3794      85
16206    192
16899    120
12274    190
23433     79
20771    165
41065     99
42025     44
16440     65
Name: price, dtype: int64


In [58]:
print("\n\nLASSO")
from sklearn.linear_model import Lasso
lasso = Lasso(alpha = 0.001, normalize=True)
lasso.fit(X_train, Price_train)
print(lasso)
print("Lasso coeffs:", lasso.coef_)
print("Lasso intercept:", lasso.intercept_)
Price_predictions = lasso.predict(X_test)
print('Lasso R squared:', lasso.score(X_test, Price_test))
print(Price_predictions[:10])
print(Price_test[:10])



LASSO
Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)
Lasso coeffs: [ 8.47490343e-08  9.12153856e+00  7.69820743e-02  1.37933299e+02
 -6.14159321e+02 -1.01645275e+02 -1.76217922e-01 -1.99931498e-01
 -3.92589516e+00 -9.12130787e-02  1.95938799e-01]
Lasso intercept: -50873.358765094345
Lasso R squared: 0.07548557444894455
[100.81230825 217.61169928 267.57537016 182.01093987 221.67401197
 126.28439247 246.7645143  172.4724498  106.05261286 105.72505774]
9630      45
3794      85
16206    192
16899    120
12274    190
23433     79
20771    165
41065     99
42025     44
16440     65
Name: price, dtype: int64


In [59]:
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

clf_tree = tree.DecisionTreeClassifier(criterion="entropy", max_depth=5)
clf_tree.fit(X_train, Price_train)
print(clf_tree)
tree_predictions = clf_tree.predict(X_test)
print(confusion_matrix(Price_test, tree_predictions))
print("f1:", f1_score(Price_test, tree_predictions, average=None))
print("f1:", f1_score(Price_test, tree_predictions, average='micro'))

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
f1: 

C:\Users\Prabhjyot\Anaconda3\Anaconda4\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.13157895 0.         0.         0.         0.
 0.05699482 0.         0.         0.         0.         0.02181818
 0.         0.         0.         0.         0.         0.
 0.         0.16091954 0.         0.16268191 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.08401254 0.         0.         0.         0.
 0.06129398 0.         0.         0.         0.         0.02564103
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.02693603 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.13309776
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.       

In [61]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(n_estimators=50, criterion='entropy')
clf_rf.fit(X_train, Price_train)
print(clf_rf)
rf_predictions = clf_rf.predict(X_test)
print(confusion_matrix(Price_test, rf_predictions))
print("f1:", f1_score(Price_test, rf_predictions, average='micro'))

MemoryError: could not allocate 80478208 bytes

In [45]:
##### KNN #####

from sklearn.neighbors import KNeighborsClassifier

clf_knn = KNeighborsClassifier(n_neighbors=3)
clf_knn.fit(X_train, Price_train)
print(clf_knn)
#knn_predictions_train = clf_knn.predict(Features_train)
knn_predictions_test = clf_knn.predict(X_test)
#print("Training CM:")
#print(confusion_matrix(Quality_train, knn_predictions_train))
#print("Training f1:", f1_score(Quality_train, knn_predictions_train, average=None))
print("Testing CM:")
print(confusion_matrix(Price_test, knn_predictions_test))
print("Testing f1:", f1_score(Price_test, knn_predictions_test, average='micro'))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')
Testing CM:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Testing f1: 0.057772321124070665


In [46]:
#### NAIVE BAYES #####

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Price_train)
print(gnb)
gnb_predictions = gnb.predict(X_test)
print(confusion_matrix(Price_test, gnb_predictions))
print("Testing f1:", f1_score(Price_test, gnb_predictions, average="micro"))

GaussianNB(priors=None, var_smoothing=1e-09)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Testing f1: 0.04228906623013437
